### ISSUE TITLE
Javascript capstone

### ISSUE THREAD

**Issue by misheck12** [EzekielUtshudi/Javascrip-Capstone-Project#21]
Below is the link to our repo.

we have two people on this project @misheck12  and @EzekielUtshudi 

https://github.com/EzekielUtshudi/Javascrip-Capstone-Project/projects/1

**Comment by Kingstalux** [comment]
Hi @misheck12 and @EzekielUtshudi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ All cards have assingnees
✅ Good job sharing the tasks equally

## Required Changes ♻️
- [x] Kindly provide the link to the project ([this link](https://github.com/EzekielUtshudi/Javascrip-Capstone-Project/projects/1)) and not the repo link 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by misheck12** [comment]
hello, @Kingstalux thanks for reviewing this project. We have worked on it.

happy coding

**Comment by Kingstalux** [comment]
Hi @misheck12 and @EzekielUtshudi,
# Status: Approved ✔️ ✔️ ✔️ 
 
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/162776255-8dda77e8-44b5-48f9-ad12-526d4728c447.gif)


Good job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
